lab_1/urls.py
from django.urls import path
from .views import index
from .views import friend_list

urlpatterns = [
    path('', index, name='index'),
    path('friends', friend_list, name='friend_list'),
    # TODO Add friends path using friend_list Views
]

lab_2/urls.py
from django.urls import path
from .views import (index, xml,json)


urlpatterns = [
        path('', index, name='index'),
        path('xml', xml, name='xml'),
        path('json', json, name='json'),
]

lab_3/urls.py
from django.urls import path
from .views import add_friend, index


urlpatterns = [
        path('', index, name='index'),
        path('add', add_friend, name='add friend')
]  

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

urlpatterns = [
        path('', index, name='index1'),
        path('add-note', add_note, name='add note'),
        path('note-list', note_list, name='note list')
]

lab_5/urls.py
from django.urls import path
from .views import index

urlpatterns = [
        path('', index, name='index'),
]

praktikum/urls.py
from django.urls import path, re_path
from django.contrib import admin
from django.urls.conf import include
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5


from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include(lab_1)),
    path('lab-2/', include(lab_2)),
    path('lab-3/', include(lab_3)),
    path('lab-4/', include(lab_4)),
    path('lab-5/', include(lab_5)),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    npm = models.CharField(max_length=10)
    dob = models.DateField()
    # TODO Implement missing attributes in Friend model

lab_2/models.py
from django.db import models

# Create your models here.

class Note(models.Model):
    To = models.CharField(max_length=100)
    From = models.CharField(max_length=100)
    Title = models.CharField(max_length=100)
    Message = models.TextField(max_length=100)

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from lab_1.models import Friend
from django import forms

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = "__all__"
        

lab_4/forms.py
from lab_2.models import Note
from django import forms

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = "__all__"

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Charles Pramudana'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002, 11, 12)  # TODO Implement this, format (Year, Month, Date)
npm = 2006596491  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all().values()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.http.response import HttpResponse 
from django.core import serializers 
from django.shortcuts import render
from .models import Note

# Create your views here.
def index(request):
    notes = Note.objects.all().values()
    response = {'notes': notes}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")
    

lab_3/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .forms import FriendForm
from lab_1.models import Friend
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/admin/login/')
def index(request):
    friends = Friend.objects.all().values()
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login/')
def add_friend(request):
    context = {}
    form = FriendForm(request.POST, request.FILES or None)

    if (form.is_valid()):
        form.save()
        return HttpResponseRedirect("/lab-3")
    
    context['form']= form
    return render(request, "lab3_form.html", context)

    # Reference: https://www.geeksforgeeks.org/django-modelform-create-form-from-models/

lab_4/views.py
from django.shortcuts import render
from lab_2.models import Note
from .forms import NoteForm
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


def index(request):
    notes = Note.objects.all().values()
    response = {'notes': notes}
    return render(request, 'lab4_index.html', response)


def note_list(request):
    notes = Note.objects.all().values()
    response = {'notes': notes}
    return render(request, 'lab4_note_list.html', response)
    
def add_note(request):
    context = {}
    form = NoteForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/lab-4")

    context['form']= form
    return render(request, "lab4_form.html", context)

    # Reference: https://www.geeksforgeeks.org/django-modelform-create-form-from-models/

lab_5/views.py
from django.shortcuts import render
from lab_2.models import Note
# Create your views here.

def index(request):
    notes = list(Note.objects.all().values_list('To'))
    nama = 'Rhoma'
    if (nama,) in notes:
        print("yes")
    print(notes)
    response = {'notes': notes}
    return render(request, 'lab5_index.html', response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      
      {% if friends %} 
        {% for friend in friends %}
        <tr>
          <td>{{ friend.name }}</td>
          <td>{{ friend.npm }}</td>
          <td>{{ friend.dob }}</td>
        </tr>
        {% endfor %}
      {% endif %}

      <!-- EXAMPLE SECTION
      <tr>
        <td>Asmara Nugi</td>
        <td>1706032156</td>
        <td>May 1, 1999</td>
      </tr>
      <tr>
        <td>Fadli Rais</td>
        <td>1706032370</td>
        <td>Sept 11, 1998</td>
      </tr>
      END SECTION -->
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>LAB-2 Charles Pramudana</title>
  </head>
  <body>
    <table border="1px solid black">
      <tr>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      
      {% if notes %} 
        {% for note in notes %}
        <tr>
          <td>{{ note.To }}</td>
          <td>{{ note.From }}</td>
          <td>{{ note.Title }}</td>
          <td>{{ note.Message }}</td>

        </tr>
        {% endfor %}
      {% endif %}
    </table>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Add Friend Form</title>
  </head>
  <body>
    <p>ADD YOUR FRIEND</p>
    <form action="" method="POST">
      {% csrf_token %}
      <label for="name">Nama:</label><br>
      <input type="text" name="name"><br>
      <br>
      <label for="npm">NPM:</label><br>
      <input type="text" name="npm"><br>
      <br>
      <label for="dob">Tanggal Lahir:</label><br>
      <input type="date" name="dob"><br>
      <br>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table border="1px solid black">
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      {% if friends %} 
        {% for friend in friends %}
        <tr>
          <td>{{ friend.name }}</td>
          <td>{{ friend.npm }}</td>
          <td>{{ friend.dob }}</td>
        </tr>
        {% endfor %}
      {% endif %}
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <title>Add Note</title>
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FEFBF3;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">LAB 4</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'add note' %}">Add Note</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index1' %}">Table-view</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'note list' %}">Card-view</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <h1>Add Note</h1>

    <div class="container">
      <form id="note-form" action="" method="POST">
        {% csrf_token %}
        <div id="form-input">
          <label for="id_To">To:</label>
          <br>
          <input type="text" name="To" maxlength="100" id="id_To">
          <br><br>
          <label for="id_From">From:</label>
          <br>
          <input type="text" name="From" maxlength="100" id="id_From">
          <br><br>
          <label for="id_Title">Title:</label>
          <br>
          <input type="text" name="Title" maxlength="100" id="id_Title">
          <br><br>
          <label for="id_Message">Message:</label>
          <br>
          <textarea name="Message" id="id_Message" cols="30" rows="10" form="note-form"></textarea>
          <br><br>
          <input type="submit" value="Submit">
        </div>
      </form>
    </div>
  </body>
</html>

lab_4/templates/lab4_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <title>All Note</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FEFBF3;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">LAB 4</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'add note' %}">Add Note</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index1' %}">Table-view</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'note list' %}">Card-view</a>
            </li>
          </ul>
        </div>
      </div>
  </nav>
  <h1 style="text-align: center; margin: 2rem auto 2rem auto;">All Messages</h1>
  <div class="container">

      <table>
        <tr>
          <th>To</th>
          <th>From</th>
          <th>Title</th>
          <th>Message</th>
        </tr>
        
        {% for note in notes %}
          <tr>
            <td>{{ note.To }}</td>
            <td>{{ note.From }}</td>
            <td>{{ note.Title }}</td>
            <td>{{ note.Message }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </body>
</html>

lab_4/templates/lab4_note_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
    <title>All Note - Card</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FEFBF3;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">LAB 4</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'add note' %}">Add Note</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index1' %}">Table-view</a>
            </li>
                
            <li class="nav-item">
              <a class="nav-link" href="{% url 'note list' %}">Card-view</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
    <h1 style="text-align: center; margin: 2rem auto 2rem auto;">All Messages</h1>

    <div class="container">
      <div class="row">
        {% for note in notes %}
          <div class="col-3 mb-3 mr-5 ml-4">
            <div class="card bg-light border-dark mb-3">
              <div class="card-body">
                <h3 class="card-title">{{ note.Title }}</h3>
                <h6 class="card-text">To: {{ note.To }}</h6>
                <h6 class="card-text">From: {{ note.From }}</h6>
                <p class="card-text">{{ note.Message}}</p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
</body>
</html>

lab_5/templates/lab5_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <title>All Note</title>
  </head>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
      $.ajax({url: "http://127.0.0.1:8000/lab-2/json", success: function(result){
      $(".container").html(result);}});
    </script>
    <h1 style="text-align: center; margin: 2rem auto 2rem auto;">All Messages</h1>
    <div class="container">

      <table>
        <tr>
          <th>To</th>
          <th>From</th>
          <th>Title</th>
          <th>Message</th>
          <th>Action</th>
        </tr>
        
        {% for note in notes %}
          <tr>
            <td>{{ note.To }}</td>
            <td>{{ note.From }}</td>
            <td>{{ note.Title }}</td>
            <td>{{ note.Message }}</td>
            <td>
                <button type="button" class="btn btn-primary btn-sm">View</button>
                <button type="button" class="btn btn-success btn-sm">Edit</button>                
                <button type="button" class="btn btn-danger btn-sm">Delete</button>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </body>
</html>